Categories:
  - Internet
License: GPL-3.0-only
SourceCode: https://github.com/christinloehner/FediSuite-Android-App
IssueTracker: https://github.com/christinloehner/FediSuite-Android-App/issues

Builds:
  - versionName: "0.9.13"
    versionCode: 913
    commit: v0.9.13
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y npm
    gradle:
      - yes
    prebuild:
      - sed -i '/org.gradle.java.home/d' gradle.properties
      - sed -i '/jvmToolchain/s/17/21/g' ../node_modules/@react-native/gradle-plugin/*/build.gradle.kts
      - sed -i 
        's/project.kotlinExtension.jvmToolchain(17)/project.kotlinExtension.jvmToolchain(21)/g'
        ../node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/JdkConfiguratorUtils.kt
      - cd ..
      - npm ci
    scandelete:
      - node_modules

UpdateCheckMode: HTTP
CurrentVersion: "0.9.13"
CurrentVersionCode: 913
